main1 : main1.c lista_ligada.c tabela_de_sim.c salas.c
		gcc -Wall -o main1 main1.c lista_ligada.c tabela_de_sim.c salas.c

testes : testes.c lista_ligada.c tabela_de_sim.c salas.c
		gcc -Wall -o testes testes.c lista_ligada.c tabela_de_sim.c salas.c

