testes : testes.c lista_ligada.c salas.c tabela_de_sim.c main1 initSalas.c aventureiro.c
	gcc -o testes testes.c lista_ligada.c salas.c tabela_de_sim.c initSalas.c aventureiro.c

main1 : main1.c lista_ligada.c salas.c tabela_de_sim.c
	gcc -o main1 main1.c lista_ligada.c salas.c tabela_de_sim.c