testes : testes.c lista_ligada.c salas.c tabela_de_sim.c initSalas.c aventureiro.c introducao.c elemento.c
	gcc -o testes testes.c lista_ligada.c salas.c tabela_de_sim.c initSalas.c aventureiro.c introducao.c elemento.c
