testes : testes.c lista_ligada.c salas.c tabela_de_sim.c init_salas.c aventureiro.c introducao.c elemento.c
	gcc -Wall -o testes testes.c lista_ligada.c salas.c tabela_de_sim.c init_salas.c aventureiro.c introducao.c elemento.c
